check copy success

diff --git a/updateSnippets b/updateSnippets
--- a/updateSnippets
+++ b/updateSnippets
@@ -4,9 +4,11 @@ clear
 
 echo "> Copying snippets into Atom..."
 
-cp $(dirname $0)/snippets.cson ~/.atom/snippets.cson
-
-echo "> ...Copy success!"
-echo "> Opening your new snippets in Atom."
-
-atom ~/.atom/snippets.cson
+if cp $(dirname $0)/snippets.cson ~/.atom/snippets.cson
+then
+  echo "> ...Copy success!"
+  echo "> Opening your new snippets in Atom."
+  atom ~/.atom/snippets.cson
+else
+  echo "> ...Failure! Exit status: $?"
+fi
